# Generated by Django 3.1.2 on 2020-10-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('is_candidate', models.BooleanField(default=False)),
                ('asipiring_position', models.CharField(default='NONE', max_length=35)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('middle_initial', models.CharField(max_length=5)),
                ('student_number', models.CharField(max_length=10)),
                ('is_Officer', models.BooleanField(default=False)),
                ('ballot_number', models.CharField(max_length=3, unique=True)),
                ('has_voted', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(max_length=100, unique=True)),
                ('voter_student_num', models.CharField(max_length=10)),
                ('votes', models.CharField(max_length=5000)),
                ('ballot_number', models.CharField(max_length=3)),
                ('date_voted', models.DateTimeField(auto_now_add=True, verbose_name='date voted')),
            ],
        ),
    ]
